services:
  auth:
    build: ../services/auth-service
    environment:
      - PORT=3001
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/notesphere
      - JWT_SECRET=dev-secret
    depends_on: [postgres]

  notes:
    build: ../services/notes-service
    environment:
      - PORT=3002
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/notesphere
      - JWT_SECRET=dev-secret
      - ELASTIC_URL=http://elasticsearch:9200
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      - MINIO_BUCKET=notes-uploads
      - MINIO_PUBLIC_ENDPOINT=http://localhost:9000
    depends_on: [postgres, elasticsearch, minio]

  gateway:
    image: nginx:1.27-alpine
    ports: ["8080:80"]
    volumes:
      - ../docker/gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [auth, notes]    # make gateway wait for auth  

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notesphere
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports: ["9200:9200"]
    volumes:
      - esdata:/usr/share/elasticsearch/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address :9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - minio:/data

volumes:
  pgdata:
  esdata:
  minio:
